import Job from "../models/Job.js";
import ATSReport from "../models/ATSReport.js";

import ApiError from "../utils/ApiError.js";

import { generateATSReport } from "./geminiService.js";

export const generateATSForApplication = async (application) => {
  // Fetch Job
  const job = await Job.findById(application.job);

  if (!job) {
    throw new ApiError(404, "Job not found.");
  }

  // Return Cached Report
  const existingReport = await ATSReport.findOne({
    candidate: application.candidate,
    job: application.job,
  });

  if (existingReport) {
    return existingReport;
  }

  // Validate Resume Snapshot
  if (!application.resumeSnapshot?.resumeText) {
    throw new ApiError(
      400,
      "Resume snapshot not found for this application."
    );
  }

  // Build Job Description
  const jobDescription = [
    job.title,
    job.description,
    ...job.requirements,
  ].join("\n\n");

  let aiReport;

  try {
    aiReport = await generateATSReport({
      resumeText: application.resumeSnapshot.resumeText,
      jobDescription,
    });
  } catch (error) {
    throw new ApiError(
      500,
      error.message || "Failed to generate AI ATS report."
    );
  }

  // Validate AI Response
  if (
    !aiReport ||
    typeof aiReport.score !== "number" ||
    !Array.isArray(aiReport.matchedSkills) ||
    !Array.isArray(aiReport.missingSkills)
  ) {
    throw new ApiError(
      500,
      "Invalid ATS report generated by AI."
    );
  }

  // Save Report
  const report = await ATSReport.create({
    candidate: application.candidate,

    job: application.job,

    score: aiReport.score,

    matchedSkills: aiReport.matchedSkills,

    missingSkills: aiReport.missingSkills,

    summary: aiReport.summary,

    review: aiReport.review,

    candidateAnalysis: aiReport.candidate,

    interviewQuestions: aiReport.interviewQuestions,

    status: "completed",

    lastGeneratedAt: new Date(),
  });

  return report;
};